### ISSUE TITLE
Skill/Item builds

### ISSUE THREAD

**Issue by ThirVondukr** [forest0xia/dota2bot-OpenHyperAI#10]
Hey, I took a brief look at how currently hero build are defined, if I understand correctly they're just hardcoded in each bot script?  
Maybe it would be possible to periodically fetch popular or manually whitelisted guides from the Steam Workshop and generate `.lua` files or any other format that you can work with here 🤔

**Comment by forest0xia** [comment]
It could be possible. But why does it matter?

You probably only see the benefit of it, the risk is much higher than the benefit that you just don't know what is a good guide to use, the duplicated items, the wrong order of items, the update in APIs and out dated guides.

Do you know if there is such api exist, and does it return the list of guides and items with Dota internal item names in correct order?

One fundamental issue is you cannot access network inside the bot script, so someone need to manually run a script outside or this script to query, filter, analyze/verify the , override existing list in lua files for each and every heroes.

TBH, it's a good thought, but I do not think it's worth the effort. We should sync the hero counter pick, hero ability upgrades order, then only after those it's the item selection, if we have a lot of time & resource.

I would recommend you to get started and try doing it yourself and I would like to see your progress and step in to help later.

**Comment by forest0xia** [comment]
You need to know bots are dumb and weak not because they don't know how to build items, but because they lack of intelligence in decision making.

I have little interest in building another script to crawl the builds and put it for bots. I would spend time in making the spell usage and item usage and fight decision making better. 

Since you raised this good point, please feel free to try making it work. I'm happy to see good ideas come true from you and by you.

**Comment by ThirVondukr** [comment]
Thanks for a very detailed reply, I think currently your bot script is the best one, bots perform in teamfight well, but lack more macro decision making, so they need some exp/gold boost, which is fine. 

I would just like to see more build variety, e.g. Lina builds as a spell caster/support, but carry Lina is quite strong in the current meta.  
I think bots should choose a build depending on their position, maybe current Lina build would make sense as pos 4/5.  

Regarding fetching item builds from the workshop - I could take a look into that, since a lot of items in builds are situational I think it's possible to just use items from the main section or two, so bots don't have to do any decision making here.

**Comment by forest0xia** [comment]
> I think bots should choose a build depending on their position, maybe current Lina build would make sense as pos 4/5.

Bots do choose item builds depending on their position right now. You mentioned you've read the code, but did you actually look at the code?
example:
https://github.com/forest0xia/dota2bot-OpenHyperAI/blob/main/bots/BotLib/hero_lina.lua#L53

You can see the builds are different for pos_1 to pos_5. You can also let the bot lina to go to mid, and see if Lina actually choose different items - she will.

**Comment by ThirVondukr** [comment]
I guess that's my bad, I somehow didn't notice it 😅

**Comment by ThirVondukr** [comment]
Yeah, maybe I stumbled upon that

**Comment by ThirVondukr** [comment]
Is there a chance I could help with anything? I mostly do python/backend work, but honestly don't have any experience with lua or dota's bot API

**Comment by forest0xia** [comment]
I honestly don't know if there is anything you can do for the bot script with python, at the moment.

I had thought about using python to build a backend server to handle live traffic for live decision making with trained ML.

But that takes a lot effort for one or two people to do. And it's not cheap. The server latency, overall cost, time of development and training is just making it impossible for us as individuals to do.

My bot uses a python backend by the way, but it's for the bots to integrate with ChatGPT APIs so bots can talk like real player after some fine tuning. The code here is just simple and no need any additional work.

That being said, if you want to help, you need to understand how LUA works. And that's simple. Because it's just a script and the people developed this script were also new to LUA or even coding. So you will see a lot of craps in the script - legacy code from uneducated devs.

I also just started to learn Lua a few months ago when I started my first commit. It's really just a matter of time and interests, and I'm glad you are willing to learn.

I have put info in the README as well as in appendix in the Customize/general.lua file for what we can improve next. Please take a look see what you are more interested about.

**Comment by forest0xia** [comment]
Maybe you can start with improving IO. io at the moment is really dumb, and that's because I only used 200 lines of code to implement its functionality.

The code there is small, simple and straightforward, you can quickly ramp up the code base and do your own creation for the bot behaviors.

**Comment by ThirVondukr** [comment]
I don't mind learning lua since it's just a scripting language and it should be similar to Python/JS, but something like https://typescripttolua.github.io/ looks very interesting too. I'll try to look into IO right now and set up a dev environment 👀

**Comment by ThirVondukr** [comment]
Seems like I wasn't able to set up a local dev environment correctly.
I've cloned repository to `dota/scripts/vscripts`, but getting an error when trying to import `game/initbots`.  
Could you help me set up a dev environment? 😅 
```
[VScript] Script Runtime Error: ...pts\bots\FunLib\override_generic\mode_laning_generic.lua:3: module 'game/botsinit' not found:
	no field package.preload['game/botsinit']Failed to find scripts\vscripts\game\botsinit.lua
stack traceback:
	[C]: in function 'require'
	...pts\bots\FunLib\override_generic\mode_laning_generic.lua:3: in main chunk
	[C]: in function 'dofile'
	...\game\dota\scripts\vscripts\bots\mode_laning_generic.lua:19: in main chunk
Failed to run script 'D:\SteamLibrary\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots\mode_laning_generic.lua'!
[VScript] Script Runtime Error: ...pts\bots\FunLib\override_generic\mode_attack_generic.lua:3: module 'game/botsinit' not found:
	no field package.preload['game/botsinit']Failed to find scripts\vscripts\game\botsinit.lua
stack traceback:
	[C]: in function 'require'
	...pts\bots\FunLib\override_generic\mode_attack_generic.lua:3: in main chunk
	[C]: in function 'dofile'
	...\game\dota\scripts\vscripts\bots\mode_attack_generic.lua:12: in main chunk
Failed to run script 'D:\SteamLibrary\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots\mode_attack_generic.lua'
```

**Comment by forest0xia** [comment]
It seems you somehow don't have that init file in your local. Were you able to play the script?

Btw, you may need to make a copy of your gameinit folder cuz I added it in the gitignore so it's not in the repo.

**Comment by forest0xia** [comment]
I know there are some libs for generating lua files using python or typescript. I've seen a lib that has integrated with dota2 scripts raw APIs and enums as well in the past - there are other scripts using the libs already. but can't recall the name on top of my head.

I felt it can take time to do the compatible check and may introduce weird bugs, and we anyway need to know how lua works in the bottom layer to make better bot scripts so I ended up didn't spend time on the 3rd party libs to generate lua.

But I do suggest you time box your effort and try it out.

**Comment by ThirVondukr** [comment]
Uh, I deleted it to clone the repo 😅 I feel pretty dumb

**Comment by ThirVondukr** [comment]
I think typescript would be more approachable and would help document internal and dota 2 API better (e.g. using imports and global declarations):
```ts
interface BotBehavior {
    SkillsComplement(this: void): void;
}

export = {
    SkillsComplement(): void {
        print("[object Object")
    }
} satisfies BotBehavior;
```
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {SkillsComplement = function()
    print("[object Object")
end}
return ____exports
```

**Comment by ThirVondukr** [comment]
You should be able to mix ts/lua files too 🤔

**Comment by forest0xia** [comment]
That file isn't hard to get. You can search for the file name in GitHub and find a copy of the folder/file to restore.

I'm not with my pc now so I can't help you atm.

**Comment by ThirVondukr** [comment]
Thanks, I'm good, I luckily only soft deleted it
