### ISSUE TITLE
 What numbers are what difficulty for "dota_bot_set_difficulty"?

### ISSUE THREAD

**Issue by Espionage724** [forest0xia/dota2bot-OpenHyperAI#13]
https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting#Bot_Difficulties says there's 6

- Passive
- Easy
- Medium
- Hard
- Unfair
- New Player

https://developer.valvesoftware.com/wiki/List_of_Dota_2_console_commands_and_variables#D says:

```
Sets all bots to a particular difficulty (0 = easy, 1 = medium, 2 = hard, 3 = unfair. 
```
But what about Passive and New Player? It seems like 0 would start at Passive and Easy being 1?

Is there a local script file that mentions the numbers? Or any way to show the bot difficulty during a match? Or any up-to-date source that mentions what numbers are what difficulty?

I want to launch Dota 2 immediately into an Unfair bot match and have this that works, and want to make sure the difficulty number is for Unfair:

```
+sv_lan 1 +dota_bot_set_difficulty 4 +dota_start_ai_game 1 +map dota
```

And is there any differences with how those difficulties work with Frebots?

**Comment by forest0xia** [comment]
TBH, I dont know and I dont really care. Just choose unfair by yourself in dota2 client. Or using the interface available if you are using anyother method to create a game. 
I only play unfair with manual selection in local lobby. Fretbots is mean to be on top of unfair bots. If you want to know how it performs against other bots below unfair, I suggest explore the games yourself.

**Comment by Espionage724** [comment]
> Just choose unfair by yourself in dota2 client. Or using the interface available if you are using anyother method to create a game.

The way I launch Dota 2, I auto-load into a bot match and skip the main menu dance entirely :p That's why I'd like to get the details of `+dota_bot_set_difficulty `down.

I wonder if there's something easy like hopping into a Unfair match from the main menu selection, and then checking a cvar to see what it reports, and comparing it to Easy/etc diffs? I might mess around with that later.

**Comment by forest0xia** [comment]
I'd appreciated if you can look into how to utilize Steam API to create a custom lobby programmatically and make it possible to invite friends with steam DIs to the lobby game, and able to select the specific script ID for the game bots.

ref:
1- https://dota2.readthedocs.io/en/stable/dota2.features.lobby.html#dota2.features.lobby.Lobby.create_practice_lobby
2- https://github.com/SteamRE/SteamKit

**Comment by forest0xia** [comment]
This is probably the only workaround that we might be able to use a remote server to host any bot script without the need of a local server. I suspect the reason/bug why most bot scripts cannot be played in remote servers are due to the ID become incorrect when loaded remotely and caused the bots to fallback to default bot script

**Comment by forest0xia** [comment]
I basically only play with friends, so anything automation or command work will have to work easily for any non-technical friends as well to keep my interest to spend any extra time thinking.

**Comment by Espionage724** [comment]
`dota_bot_practice_difficulty` reports theses for difficulty (start bot match from main menu -> Console):

- `1` = Easy
- `2` = Medium
- `3` = Hard
- `4` = Unfair
