### ISSUE TITLE
 Script Runtime Error

### ISSUE THREAD

**Issue by christiandwi** [forest0xia/dota2bot-OpenHyperAI#17]
Hello, i got error when starting this script from local

 [VScript] Script Runtime Error: attempt to index a number value
 [VScript] Message count limit of 10 hit. Subsequent duplicate messages will be squelched.

sorry but i don't see any clear error messages on what line the error is, i think it has something to do with the latest commit, could you please check on it?

**Comment by forest0xia** [comment]
Fixed. try updating or re-subscribing the script.

**Comment by christiandwi** [comment]
Thanks! Fixed now
