### ISSUE TITLE
luna  bug skill.

### ISSUE THREAD

**Issue by jojo1521** [forest0xia/dota2bot-OpenHyperAI#19]
![Screenshot_2](https://github.com/user-attachments/assets/18e9c92a-2540-4808-907e-cc47cc26ecea)

**Comment by christiandwi** [comment]
I can't reproduce this issue, are you sure you are using this script? Seems like the bot's name is off...

**Comment by forest0xia** [comment]
@jojo1521 you are not using the script correctly. please try to re-subscribe the script and ensure the bot names have suffix "OHA".

@christiandwi Thanks, exactly.
