### ISSUE TITLE
Best practice to keep up-to-date

### ISSUE THREAD

**Issue by hetong007** [forest0xia/dota2bot-OpenHyperAI#27]
Hello, as someone who have looked into & customized SiriusAI code, I whole-heartly appreciate your efforts put into this project, thank you!

My question is, since I want to use fretbot thus need local lobby, I can git clone this project to the corresponding folder of bot scripts, but is there any other things I need to do to "install" the fretbot if it gets updated as well?

**Comment by forest0xia** [comment]
Check out this to keep the script auto updating https://github.com/forest0xia/dota2bot-OpenHyperAI/blob/main/install-to-vscript/README.md
If you worry about what does the .bat file do, can just view its source code or do the linking yourself by following the instructions on the bottom of the guides.

**Comment by hetong007** [comment]
Thanks, a follow up question: I may have local modifications for lobby games but those modifications might be overridden by the renaming-&-linking process. Do you have suggestions on how to update the main scripts without touching the local modifications?

**Comment by forest0xia** [comment]
Unfortunately I don't have a good suggestion for this. My updates may touch every file as I keep developing/refactoring stuff. so I'd suggest you either contribute to this repo if you think the local modification is good to share with other players, or keep a copy of the modified files you have in a different place and replace back when those got overridden.

**Comment by forest0xia** [comment]
Actually, you can clone my repo to your local, replace whatever is there in your vscript. And then create new branches to manage the different modification versions you have while still able to quickly get the changes from me. Once a new release is there you can simply commit it to main branch and merge with other branches

**Comment by forest0xia** [comment]
But I'd still suggest you to contribute together, it's good to have more active people making meaningful updates like a remote team for a better bot experience. Try to use typescript first for making modifications.

**Comment by hetong007** [comment]
Yeah thanks for the suggestions. One thing I'd like to make sure is that the github updates reflects in the steam workshop subscription -- if so, I can ignore the bat script but just maintain a forked version locally. 

Regarding the contribution, yes I totally agree. I've been working on open source projects some years ago. Still, I may need to think what are the aspects that I'm capable of contributing to, and also learning typescript as well.

**Comment by forest0xia** [comment]
> the github updates reflects in the steam workshop subscription
There is no automation for this, so there is no guarantee. I sometimes commit to one but forget or feel lazy to update the other. But in general they should be in sync - probably with the SLA around 1 week at most.
