### ISSUE TITLE
[Feature request] Respect TPs 

### ISSUE THREAD

**Issue by forest0xia** [forest0xia/dota2bot-OpenHyperAI#49]
Is it even possible for bots to "see" if there are enemies TPing to a place, when a human player can absolutely see the TP and decide to retreat to avoid death.

**Comment by christiandwi** [comment]
I don't see any API from valve to achieve this, do you have any suggestion on what should we use to get the tp-ing number of heroes?

**Comment by forest0xia** [comment]
Yeah, so I have a workaround thinking - Check if there's any enemy that we can see that have TP modifiers on them and facing the target tower location, which means they are likely TPing to defend.

**Comment by forest0xia** [comment]
> { { playerid, location, time_remaining }, ... } GetIncomingTeleports()
	Gets a table of all the teleports that are visibly happening.
