### ISSUE TITLE
[Feature request] Determine enemy roles better

### ISSUE THREAD

**Issue by forest0xia** [forest0xia/dota2bot-OpenHyperAI#50]
Right now there is no accurate role detection. The current way is by checking the laning and hero unit name. But this is not accurate. We could, in early game use this strategy temporarily, in mid-late games we should use, for example total networth/offensive power to determine enemy roles

**Comment by christiandwi** [comment]
Sorry this is out of topic a little bit, but is there any script to set the default facet? I can't find it on valve official scripting.

This would be really helpful as first facet of some heroes are trash right now and some cores need specific facet to be good
