### ISSUE TITLE
!pos x command doesn't work all the time

### ISSUE THREAD

**Issue by hondacbr600** [forest0xia/dota2bot-OpenHyperAI#54]
In CM, when a bot is the captain, bots doesn't respond to !pos x command. I'm on the second slot in the lobby, still no luck 🤷‍♂️

**Comment by forest0xia** [comment]
so what. why do you want to use CM and swap roles. there is no script out there provide better UX than mine now and i do not have time to fix this for CM which no many users care, at least i do not really play CM. As i mentioned in https://steamcommunity.com/workshop/filedetails/discussion/3246316298/4334231305373971730/, if you want to use CM, know there are issues, and you can always use customize lua file.

Free feel to help me fix it

**Comment by hondacbr600** [comment]
I mean, the command should be forceable. If the player says he wants the X lane, bots should yield no matter what.
But if you say it's a lot of work to do, then it is what it is.

P.S. I'm no dev by any means, but I'm curious, how I can help?

**Comment by forest0xia** [comment]
btw, you are probably not using the latest version.

**Comment by forest0xia** [comment]
> I mean, the command should be forceable. If the player says he wants the X lane, bots should yield no matter what. But if you say it's a lot of work to do, then it is what it is.
> 
> P.S. I'm no dev by any means, but I'm curious, how I can help?

Take a look at my post linked above. Bot should respond to !pos. if its not, you are not using the latest versions which had been released for months.

**Comment by hondacbr600** [comment]
How can I check, I created a SymLink to the local dev, shouldn't this be enough?

**Comment by hondacbr600** [comment]
Anyway, dir /AL /S did the trick:

C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts>dir /AL /S
 Volume in drive C has no label.
 Volume Serial Number is ****-****

 Directory of C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts

07/28/2024  12:42 PM    <SYMLINKD>     bots [C:\Program Files (x86)\Steam\steamapps\workshop\content\570\3246316298]
               0 File(s)              0 bytes

     Total Files Listed:
               0 File(s)              0 bytes
               1 Dir(s)  371,113,955,328 bytes free

**Comment by forest0xia** [comment]
see the change log. https://steamcommunity.com/sharedfiles/filedetails/changelog/3246316298

bots will announce the script version in the beginning of the game. the latest version should be 2024/10/19

**Comment by forest0xia** [comment]
> I mean, the command should be forceable. If the player says he wants the X lane, bots should yield no matter what.

well, there are a lot of tech difficulty behind it which is why there isnt a lot, or any bot script can do it even now except mine. All developers are small, but guess what why there is no perfect, working as we wanted, script available? because it's easy to think, easy to say, but nearly impossible to do, any worth nearly nothing even if its done.

**Comment by hondacbr600** [comment]
Yeah, this is the one 0.7.37d - 2024/10/19

**Comment by forest0xia** [comment]
> Yeah, this is the one 0.7.37d - 2024/10/19

I think you have a bug in your local version, and i do not know if its because you changed some files or Valve failed to update the files for you. But you can try to download and override the files from github, or reinstall dota. Note there is a caching issue for dota2 that even if you re-subscript the scirpt, it wont get updated or even downloaded correctly

**Comment by hondacbr600** [comment]
btw, what should I download if there are no releases/packages?
