### ISSUE TITLE
[Feature request] Disable pinging.

### ISSUE THREAD

**Issue by hondacbr600** [forest0xia/dota2bot-OpenHyperAI#59]
Bots doesn't have good awareness, for example, I would trade any day enemy t3 for our t2. But they keep pinging "Come defend".
Since you can't mute bots, it's really annoying.

**Comment by forest0xia** [comment]
I reduced the ping frequency from every 3s to 6s in the latest released version.

This ping is not just for you but for other bots as well. So I wont simply remove it unless you give a better idea

**Comment by hondacbr600** [comment]
idk, command to disable it or set the frequency on-demand. If the player chooses to, why not?

**Comment by forest0xia** [comment]
Because it doesn't bother me atm I don't feel it's necessary to spend my time on this. Try the new version in workshop, and feel free to raise a cr if that still is a problem for you. 

I personally don't think I will add a command for this
